Minimal reproduction of issue
This will fail with a cryptic error like:
```
ERROR: /home/joneshf/.cache/bazel/_bazel_joneshf/82029ba054c9125cad66aaa14166c07e/external/rules_haskell/tools/runfiles/BUILD.bazel:18:1: output 'external/rules_haskell/tools/runfiles/.hpc/externalZSrulesZUhaskellZStoolsZSrunfilesZSrunfiles/Bazel.Runfiles.mix' was not created
```

The issue is that the directory to find the `mix` files isn't being
created correctly. There's a path separator missing between the
workspace root and the package:

```console
$ tail bazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/extra_args_runfiles_HaskellBuildLibrary
-ibazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/src
-optP@bazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/optp_args_runfiles
-this-unit-id
externalZSrulesZUhaskellZStoolsZSrunfilesZSrunfiles
-optP-DCURRENT_PACKAGE_KEY="externalZSrulesZUhaskellZStoolsZSrunfilesZSrunfiles"
external/rules_haskell/tools/runfiles/src/Bazel/Runfiles.hs
-dynamic-too
-fhpc
-hpcdir
bazel-out/k8-fastbuild/bin/external/rules_haskelltools/runfiles/.hpc
```

In particular,
`bazel-out/k8-fastbuild/bin/external/rules_haskelltools/runfiles/.hpc`
should be
`bazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/.hpc`.